# Site Build Settings

# jekyll-paginate configuration
paginate:            5
paginate_path: "projects/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
#url: https://ctechfilmuniversity.github.io/
title:		           "CTech works"
description:	       "a webpage to share projects made "
author:              "Creative Technologies students"
# icon
logo:                /assets/img/CTech_Originals/ctech-logo.png 
header-image:        /assets/img/CTech_Originals/ctech-header-2.png 

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
