# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: '' # 'UA-112060364-2'

menu:
- {name: '1st Semester', folder: 'pages', file: 'facts.html'}
- {name: '2nd Semester', folder: 'pages', file: 'resources.html'}
- {name: '3rd Semester', folder: 'pages', file: 'sample-posts.html'}
- {name: '4th Semester', folder: 'pages', file: 'documentation.html'}
- {name: 'Other', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/@ctech_filmuni'}
- {icon: 'facebook', link: 'https://www.facebook.com/ctech.filmuniversity'}
- {icon: 'instagram', link: 'https://instagram.com/@ctech_filmuniversity'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
